# Custom Language File for Launcher Customizer

[ejs.app]
title = "OmegaMC Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.omegamc.it"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU OMEGAMC LAUNCHER"
welcomeDescription = ""
welcomeDescCTA = "Copyright © 2025 OmegaMC Studios"
